### ISSUE TITLE
Installation + Dependencies

### ISSUE THREAD

**Issue by matzech** [martinbiel/LShapedSolvers.jl#2]
Hi @martinbiel ,

very interesting package! 👍 

I struggled a little bit to install all the required dependencies for the LShapedSolvers and tried it with 0.6,0.7 and 1.0. What is the recommended way to install the package and its dependencies?

**Comment by martinbiel** [comment]
Hey!

I am actively working on it so it is prone to changes. I have a major refactoring branch locally that will soon be pushed to master. Afterwards, I could consider tagging a stable release.

With that said, the master branch should always be compatible with the master branch of [StochasticPrograms](https://github.com/martinbiel/StochasticPrograms.jl). Also, I have not made it compatible with the latest version of JuMP yet. Hence, the following:
```julia
pkg> add JuMP@0.18.5
pkg> add StochasticPrograms#master
pkg> add https://github.com/martinbiel/LShapedSolvers.jl#master
```
should give a functional version of the package. Hope this helps.
